### ISSUE TITLE
Undefined function 'sparse' for input arguments of type 'single'.

### ISSUE THREAD

**Issue by anassnouri** [rsong/CFSCNN#1]

**Comment by anassnouri** [comment]
Hi,
Thank you for sharing your code.
Nn perform_mesh_smoothing.m, replace D = spdiags( full(sum(W,2).^(-1)),0,n,n) ;  by D = spdiags( full(sum(W,2).^(-1)),0,double(n),double(n)) ;  in order to avoir the error in object.
Best regards.

**Comment by rsong** [comment]
Hi Anass,

Thanks for the correction. Yes just convert single to double type.

Ran

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Anass Nouri<mailto:notifications@github.com>
发送时间: 2021年1月26日 18:09
收件人: rsong/CFSCNN<mailto:CFSCNN@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [rsong/CFSCNN] Undefined function 'sparse' for input arguments of type 'single'. (#1)


in perform_mesh_smoothing.m, replace D = spdiags( full(sum(W,2).^(-1)),0,n,n) ; by D = spdiags( full(sum(W,2).^(-1)),0,double(n),double(n)) ; .
Best regards.

―
